name: Generate Resume PDF

on:
  push:
    branches: [main, master]
    paths:
      - "index.html" # Assuming your resume HTML file is named index.html

jobs:
  convert_to_pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for proper versioning

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          npm init -y
          npm install puppeteer

      - name: Create PDF generation script
        run: |
          cat > generate-pdf.js << 'EOL'
          const puppeteer = require('puppeteer');
          const fs = require('fs');
          const path = require('path');

          (async () => {
            // Launch browser with specific settings for PDF generation
            const browser = await puppeteer.launch({
              headless: 'new',
              args: ['--no-sandbox', '--disable-setuid-sandbox']
            });
            
            const page = await browser.newPage();
            
            // Read HTML file
            const htmlPath = path.join(process.cwd(), 'index.html');
            const html = fs.readFileSync(htmlPath, 'utf8');
            
            // Set content and wait for everything to load
            await page.setContent(html, { waitUntil: 'networkidle0' });
            
            // Add print stylesheet
            await page.addStyleTag({
              content: `
                @page {
                  size: A4 portrait;
                  margin: 1.3cm 1.6cm 1.4cm;
                }
                body {
                  -webkit-print-color-adjust: exact !important;
                  print-color-adjust: exact !important;
                }
                .nav-wrapper, .back-to-top, .theme-toggle, .print-button, .mobile-menu-toggle, footer {
                  display: none !important;
                }
              `
            });
            
            // Generate PDF with specific settings
            await page.pdf({
              path: 'chakradhar-reddy-d.pdf',
              format: 'A4',
              printBackground: true,
              displayHeaderFooter: false,
              margin: {
                top: '1.3cm',
                right: '1.6cm',
                bottom: '1.4cm',
                left: '1.6cm'
              }
            });
            
            await browser.close();
            console.log('PDF created successfully!');
          })();
          EOL

      - name: Generate PDF
        run: node generate-pdf.js

      - name: Setup Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and push if changed
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git add chakradhar-reddy-d.pdf
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update resume PDF [skip ci]"
            git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
          fi
